### ISSUE TITLE
Running Jenkins on Base4 (The Testing Server)

### ISSUE THREAD

**Issue by savarmehrotra** [vlead/continuous-integration#4]
The primary concern here is that how to provide a JRE to run the Jenkins CI tool on our servers since they aren't Java Application servers by default. In case this issue isn't resolved containerizing the application might have to be considered.

**Comment by psrikar97** [comment]
Container was created and JDK was installed on the container and Jenkins CI was installed too

**Comment by ksripathi** [comment]
when build runs throwing following error 
`wget http://orgmode.org/org-8.2.10.tar.gz

--2017-06-12 02:57:05--  http://orgmode.org/org-8.2.10.tar.gz

Resolving orgmode.org (orgmode.org)... 104.239.132.130
Connecting to orgmode.org (orgmode.org)|104.239.132.130|:80... failed: Connection refused.
tangle-make:23: recipe for target 'check-org' failed
make[1]: *** [check-org] Error 4
checking for literate support ...
echo "pwd=..."
pwd=...
echo /var/lib/jenkins/workspace/lab-data-service
/var/lib/jenkins/workspace/lab-data-service
Literate support code already present
(ln -sf literate-tools/elisp; \
ln -sf ../literate-tools/org-templates src; \
ln -sf ../literate-tools/style src)
rm -rf build
rm: cannot remove 'build/docs': Permission denied
rm: cannot remove 'build/code/VERSION': Permission denied
tangle-make:37: recipe for target 'init' failed
make[1]: *** [init] Error 1
allow these to fail since the parent folder may not have a git repo.
echo -n "Built from commit: " > build/code/VERSION
/bin/sh: 1: cannot create build/code/VERSION: Permission denied
tangle-make:66: recipe for target 'write-version' failed
make[1]: *** [write-version] Error 2
make[1]: Target 'all' not remade because of errors.
make[1]: Leaving directory '/var/lib/jenkins/workspace/lab-data-service'
makefile:16: recipe for target 'build' failed
make: *** [build] Error 2
Build step 'Execute shell' marked build as failure

Finished: FAILURE
`
